# See https://github.com/golangci/golangci-lint#config-file
run:
  concurrency: 4
  timeout: 10m
  issue-exit-code: 1
  tests: true

linters:
  disable-all: true
  fast: false
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - promlinter
    - revive
    - rowserrcheck
    - tenv
    - typecheck
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - whitespace
    - wsl

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    max-complexity: 10
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 2.0
  decorder:
    # Required order of `type`, `const`, `var` and `func` declarations inside a file.
    # Default: types before constants before variables before functions.
    dec-order:
      - type
      - const
      - var
      - func
    # If true, order of declarations is not checked at all.
    # Default: true (disabled)
    disable-dec-order-check: false
    # If true, `init` func can be anywhere in file (does not have to be declared before all other functions).
    # Default: true (disabled)
    disable-init-func-first-check: false
    # If true, multiple global `type`, `const` and `var` declarations are allowed.
    # Default: true (disabled)
    disable-dec-num-check: false
  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 80
